"""add product discount_percent

Revision ID: 14ee931e8a36
Revises: d6be54f9570e
Create Date: 2026-07-14 17:30:06.208720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '14ee931e8a36'
down_revision: Union[str, None] = 'd6be54f9570e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'discount_percent', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('discount_percent')

    # ### end Alembic commands ###
